#负责调整配置 behavior
spring:
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
  datasource:
    # $后面的是在AWS上的隐藏密码，可以自己设置
    url: jdbc:postgresql://${DATABASE_URL:localhost}:5432/onlineorder
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
    #现在db都是通过connectionPool连接 one popular connectionPool is HikariPool
  #pick up init.sql script every runtime
  sql:
    init:
      mode: ${INIT_DB:always}
      schema-locations: "classpath:database-init.sql"
      #classpath means they are in the same folder
  cache:
    caffeine:
      spec: expireAfterWrite=60s
      #After adding dependency in build.gradle, we need to configure the existence time for cache

logging:
  level:
    org.apache.coyote.http11.Http11InputBuffer: DEBUG #Incoming HTTP request
    org.springframework.jdbc.core: DEBUG # SQL